# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aem < Formula
  desc "Command line tool for AEM"
  homepage "https://github.com/jlentink/aem"
  version "1.0.0rc17"
  license "GPL-2.0 License"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jlentink/aem/releases/download/1.0.0rc17/aem_Darwin_x86_64.tar.gz"
    sha256 "14476b61678c7decc64b388c5895aea0ffbb4224e42ea78fc14ac2beec4eb293"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jlentink/aem/releases/download/1.0.0rc17/aem_Linux_x86_64.tar.gz"
    sha256 "313df71a64dfc269722042c8cefba297a30a23d55ea206c9d9e50c473a5b0d00"
  end

  depends_on "go"

  def install
    bin.install "aem"
    bash_completion.install "completions/aem.bash" => "aem"
    zsh_completion.install "completions/aem.zsh" => "_aem"
  end

  test do
    system "#{bin}/aem -v"
  end
end
